/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.type.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Weather extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5353871768177202594L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Weather\",\"namespace\":\"org.example.type.avro\",\"fields\":[{\"name\":\"MinTemp\",\"type\":[\"null\",\"string\"]},{\"name\":\"MaxTemp\",\"type\":[\"null\",\"string\"]},{\"name\":\"Rainfall\",\"type\":[\"null\",\"string\"]},{\"name\":\"Evaporation\",\"type\":[\"null\",\"string\"]},{\"name\":\"Sunshine\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindGustDir\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindGustSpeed\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindDir9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindDir3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindSpeed9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"WindSpeed3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"Humidity9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"Humidity3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"Pressure9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"Pressure3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"Cloud9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"Cloud3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"Temp9am\",\"type\":[\"null\",\"string\"]},{\"name\":\"Temp3pm\",\"type\":[\"null\",\"string\"]},{\"name\":\"RainToday\",\"type\":[\"null\",\"string\"]},{\"name\":\"RISK_MM\",\"type\":[\"null\",\"string\"]},{\"name\":\"RainTomorrow\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence MinTemp;
  @Deprecated public java.lang.CharSequence MaxTemp;
  @Deprecated public java.lang.CharSequence Rainfall;
  @Deprecated public java.lang.CharSequence Evaporation;
  @Deprecated public java.lang.CharSequence Sunshine;
  @Deprecated public java.lang.CharSequence WindGustDir;
  @Deprecated public java.lang.CharSequence WindGustSpeed;
  @Deprecated public java.lang.CharSequence WindDir9am;
  @Deprecated public java.lang.CharSequence WindDir3pm;
  @Deprecated public java.lang.CharSequence WindSpeed9am;
  @Deprecated public java.lang.CharSequence WindSpeed3pm;
  @Deprecated public java.lang.CharSequence Humidity9am;
  @Deprecated public java.lang.CharSequence Humidity3pm;
  @Deprecated public java.lang.CharSequence Pressure9am;
  @Deprecated public java.lang.CharSequence Pressure3pm;
  @Deprecated public java.lang.CharSequence Cloud9am;
  @Deprecated public java.lang.CharSequence Cloud3pm;
  @Deprecated public java.lang.CharSequence Temp9am;
  @Deprecated public java.lang.CharSequence Temp3pm;
  @Deprecated public java.lang.CharSequence RainToday;
  @Deprecated public java.lang.CharSequence RISK_MM;
  @Deprecated public java.lang.CharSequence RainTomorrow;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Weather() {}

  /**
   * All-args constructor.
   * @param MinTemp The new value for MinTemp
   * @param MaxTemp The new value for MaxTemp
   * @param Rainfall The new value for Rainfall
   * @param Evaporation The new value for Evaporation
   * @param Sunshine The new value for Sunshine
   * @param WindGustDir The new value for WindGustDir
   * @param WindGustSpeed The new value for WindGustSpeed
   * @param WindDir9am The new value for WindDir9am
   * @param WindDir3pm The new value for WindDir3pm
   * @param WindSpeed9am The new value for WindSpeed9am
   * @param WindSpeed3pm The new value for WindSpeed3pm
   * @param Humidity9am The new value for Humidity9am
   * @param Humidity3pm The new value for Humidity3pm
   * @param Pressure9am The new value for Pressure9am
   * @param Pressure3pm The new value for Pressure3pm
   * @param Cloud9am The new value for Cloud9am
   * @param Cloud3pm The new value for Cloud3pm
   * @param Temp9am The new value for Temp9am
   * @param Temp3pm The new value for Temp3pm
   * @param RainToday The new value for RainToday
   * @param RISK_MM The new value for RISK_MM
   * @param RainTomorrow The new value for RainTomorrow
   */
  public Weather(java.lang.CharSequence MinTemp, java.lang.CharSequence MaxTemp, java.lang.CharSequence Rainfall, java.lang.CharSequence Evaporation, java.lang.CharSequence Sunshine, java.lang.CharSequence WindGustDir, java.lang.CharSequence WindGustSpeed, java.lang.CharSequence WindDir9am, java.lang.CharSequence WindDir3pm, java.lang.CharSequence WindSpeed9am, java.lang.CharSequence WindSpeed3pm, java.lang.CharSequence Humidity9am, java.lang.CharSequence Humidity3pm, java.lang.CharSequence Pressure9am, java.lang.CharSequence Pressure3pm, java.lang.CharSequence Cloud9am, java.lang.CharSequence Cloud3pm, java.lang.CharSequence Temp9am, java.lang.CharSequence Temp3pm, java.lang.CharSequence RainToday, java.lang.CharSequence RISK_MM, java.lang.CharSequence RainTomorrow) {
    this.MinTemp = MinTemp;
    this.MaxTemp = MaxTemp;
    this.Rainfall = Rainfall;
    this.Evaporation = Evaporation;
    this.Sunshine = Sunshine;
    this.WindGustDir = WindGustDir;
    this.WindGustSpeed = WindGustSpeed;
    this.WindDir9am = WindDir9am;
    this.WindDir3pm = WindDir3pm;
    this.WindSpeed9am = WindSpeed9am;
    this.WindSpeed3pm = WindSpeed3pm;
    this.Humidity9am = Humidity9am;
    this.Humidity3pm = Humidity3pm;
    this.Pressure9am = Pressure9am;
    this.Pressure3pm = Pressure3pm;
    this.Cloud9am = Cloud9am;
    this.Cloud3pm = Cloud3pm;
    this.Temp9am = Temp9am;
    this.Temp3pm = Temp3pm;
    this.RainToday = RainToday;
    this.RISK_MM = RISK_MM;
    this.RainTomorrow = RainTomorrow;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MinTemp;
    case 1: return MaxTemp;
    case 2: return Rainfall;
    case 3: return Evaporation;
    case 4: return Sunshine;
    case 5: return WindGustDir;
    case 6: return WindGustSpeed;
    case 7: return WindDir9am;
    case 8: return WindDir3pm;
    case 9: return WindSpeed9am;
    case 10: return WindSpeed3pm;
    case 11: return Humidity9am;
    case 12: return Humidity3pm;
    case 13: return Pressure9am;
    case 14: return Pressure3pm;
    case 15: return Cloud9am;
    case 16: return Cloud3pm;
    case 17: return Temp9am;
    case 18: return Temp3pm;
    case 19: return RainToday;
    case 20: return RISK_MM;
    case 21: return RainTomorrow;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MinTemp = (java.lang.CharSequence)value$; break;
    case 1: MaxTemp = (java.lang.CharSequence)value$; break;
    case 2: Rainfall = (java.lang.CharSequence)value$; break;
    case 3: Evaporation = (java.lang.CharSequence)value$; break;
    case 4: Sunshine = (java.lang.CharSequence)value$; break;
    case 5: WindGustDir = (java.lang.CharSequence)value$; break;
    case 6: WindGustSpeed = (java.lang.CharSequence)value$; break;
    case 7: WindDir9am = (java.lang.CharSequence)value$; break;
    case 8: WindDir3pm = (java.lang.CharSequence)value$; break;
    case 9: WindSpeed9am = (java.lang.CharSequence)value$; break;
    case 10: WindSpeed3pm = (java.lang.CharSequence)value$; break;
    case 11: Humidity9am = (java.lang.CharSequence)value$; break;
    case 12: Humidity3pm = (java.lang.CharSequence)value$; break;
    case 13: Pressure9am = (java.lang.CharSequence)value$; break;
    case 14: Pressure3pm = (java.lang.CharSequence)value$; break;
    case 15: Cloud9am = (java.lang.CharSequence)value$; break;
    case 16: Cloud3pm = (java.lang.CharSequence)value$; break;
    case 17: Temp9am = (java.lang.CharSequence)value$; break;
    case 18: Temp3pm = (java.lang.CharSequence)value$; break;
    case 19: RainToday = (java.lang.CharSequence)value$; break;
    case 20: RISK_MM = (java.lang.CharSequence)value$; break;
    case 21: RainTomorrow = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'MinTemp' field.
   * @return The value of the 'MinTemp' field.
   */
  public java.lang.CharSequence getMinTemp() {
    return MinTemp;
  }

  /**
   * Sets the value of the 'MinTemp' field.
   * @param value the value to set.
   */
  public void setMinTemp(java.lang.CharSequence value) {
    this.MinTemp = value;
  }

  /**
   * Gets the value of the 'MaxTemp' field.
   * @return The value of the 'MaxTemp' field.
   */
  public java.lang.CharSequence getMaxTemp() {
    return MaxTemp;
  }

  /**
   * Sets the value of the 'MaxTemp' field.
   * @param value the value to set.
   */
  public void setMaxTemp(java.lang.CharSequence value) {
    this.MaxTemp = value;
  }

  /**
   * Gets the value of the 'Rainfall' field.
   * @return The value of the 'Rainfall' field.
   */
  public java.lang.CharSequence getRainfall() {
    return Rainfall;
  }

  /**
   * Sets the value of the 'Rainfall' field.
   * @param value the value to set.
   */
  public void setRainfall(java.lang.CharSequence value) {
    this.Rainfall = value;
  }

  /**
   * Gets the value of the 'Evaporation' field.
   * @return The value of the 'Evaporation' field.
   */
  public java.lang.CharSequence getEvaporation() {
    return Evaporation;
  }

  /**
   * Sets the value of the 'Evaporation' field.
   * @param value the value to set.
   */
  public void setEvaporation(java.lang.CharSequence value) {
    this.Evaporation = value;
  }

  /**
   * Gets the value of the 'Sunshine' field.
   * @return The value of the 'Sunshine' field.
   */
  public java.lang.CharSequence getSunshine() {
    return Sunshine;
  }

  /**
   * Sets the value of the 'Sunshine' field.
   * @param value the value to set.
   */
  public void setSunshine(java.lang.CharSequence value) {
    this.Sunshine = value;
  }

  /**
   * Gets the value of the 'WindGustDir' field.
   * @return The value of the 'WindGustDir' field.
   */
  public java.lang.CharSequence getWindGustDir() {
    return WindGustDir;
  }

  /**
   * Sets the value of the 'WindGustDir' field.
   * @param value the value to set.
   */
  public void setWindGustDir(java.lang.CharSequence value) {
    this.WindGustDir = value;
  }

  /**
   * Gets the value of the 'WindGustSpeed' field.
   * @return The value of the 'WindGustSpeed' field.
   */
  public java.lang.CharSequence getWindGustSpeed() {
    return WindGustSpeed;
  }

  /**
   * Sets the value of the 'WindGustSpeed' field.
   * @param value the value to set.
   */
  public void setWindGustSpeed(java.lang.CharSequence value) {
    this.WindGustSpeed = value;
  }

  /**
   * Gets the value of the 'WindDir9am' field.
   * @return The value of the 'WindDir9am' field.
   */
  public java.lang.CharSequence getWindDir9am() {
    return WindDir9am;
  }

  /**
   * Sets the value of the 'WindDir9am' field.
   * @param value the value to set.
   */
  public void setWindDir9am(java.lang.CharSequence value) {
    this.WindDir9am = value;
  }

  /**
   * Gets the value of the 'WindDir3pm' field.
   * @return The value of the 'WindDir3pm' field.
   */
  public java.lang.CharSequence getWindDir3pm() {
    return WindDir3pm;
  }

  /**
   * Sets the value of the 'WindDir3pm' field.
   * @param value the value to set.
   */
  public void setWindDir3pm(java.lang.CharSequence value) {
    this.WindDir3pm = value;
  }

  /**
   * Gets the value of the 'WindSpeed9am' field.
   * @return The value of the 'WindSpeed9am' field.
   */
  public java.lang.CharSequence getWindSpeed9am() {
    return WindSpeed9am;
  }

  /**
   * Sets the value of the 'WindSpeed9am' field.
   * @param value the value to set.
   */
  public void setWindSpeed9am(java.lang.CharSequence value) {
    this.WindSpeed9am = value;
  }

  /**
   * Gets the value of the 'WindSpeed3pm' field.
   * @return The value of the 'WindSpeed3pm' field.
   */
  public java.lang.CharSequence getWindSpeed3pm() {
    return WindSpeed3pm;
  }

  /**
   * Sets the value of the 'WindSpeed3pm' field.
   * @param value the value to set.
   */
  public void setWindSpeed3pm(java.lang.CharSequence value) {
    this.WindSpeed3pm = value;
  }

  /**
   * Gets the value of the 'Humidity9am' field.
   * @return The value of the 'Humidity9am' field.
   */
  public java.lang.CharSequence getHumidity9am() {
    return Humidity9am;
  }

  /**
   * Sets the value of the 'Humidity9am' field.
   * @param value the value to set.
   */
  public void setHumidity9am(java.lang.CharSequence value) {
    this.Humidity9am = value;
  }

  /**
   * Gets the value of the 'Humidity3pm' field.
   * @return The value of the 'Humidity3pm' field.
   */
  public java.lang.CharSequence getHumidity3pm() {
    return Humidity3pm;
  }

  /**
   * Sets the value of the 'Humidity3pm' field.
   * @param value the value to set.
   */
  public void setHumidity3pm(java.lang.CharSequence value) {
    this.Humidity3pm = value;
  }

  /**
   * Gets the value of the 'Pressure9am' field.
   * @return The value of the 'Pressure9am' field.
   */
  public java.lang.CharSequence getPressure9am() {
    return Pressure9am;
  }

  /**
   * Sets the value of the 'Pressure9am' field.
   * @param value the value to set.
   */
  public void setPressure9am(java.lang.CharSequence value) {
    this.Pressure9am = value;
  }

  /**
   * Gets the value of the 'Pressure3pm' field.
   * @return The value of the 'Pressure3pm' field.
   */
  public java.lang.CharSequence getPressure3pm() {
    return Pressure3pm;
  }

  /**
   * Sets the value of the 'Pressure3pm' field.
   * @param value the value to set.
   */
  public void setPressure3pm(java.lang.CharSequence value) {
    this.Pressure3pm = value;
  }

  /**
   * Gets the value of the 'Cloud9am' field.
   * @return The value of the 'Cloud9am' field.
   */
  public java.lang.CharSequence getCloud9am() {
    return Cloud9am;
  }

  /**
   * Sets the value of the 'Cloud9am' field.
   * @param value the value to set.
   */
  public void setCloud9am(java.lang.CharSequence value) {
    this.Cloud9am = value;
  }

  /**
   * Gets the value of the 'Cloud3pm' field.
   * @return The value of the 'Cloud3pm' field.
   */
  public java.lang.CharSequence getCloud3pm() {
    return Cloud3pm;
  }

  /**
   * Sets the value of the 'Cloud3pm' field.
   * @param value the value to set.
   */
  public void setCloud3pm(java.lang.CharSequence value) {
    this.Cloud3pm = value;
  }

  /**
   * Gets the value of the 'Temp9am' field.
   * @return The value of the 'Temp9am' field.
   */
  public java.lang.CharSequence getTemp9am() {
    return Temp9am;
  }

  /**
   * Sets the value of the 'Temp9am' field.
   * @param value the value to set.
   */
  public void setTemp9am(java.lang.CharSequence value) {
    this.Temp9am = value;
  }

  /**
   * Gets the value of the 'Temp3pm' field.
   * @return The value of the 'Temp3pm' field.
   */
  public java.lang.CharSequence getTemp3pm() {
    return Temp3pm;
  }

  /**
   * Sets the value of the 'Temp3pm' field.
   * @param value the value to set.
   */
  public void setTemp3pm(java.lang.CharSequence value) {
    this.Temp3pm = value;
  }

  /**
   * Gets the value of the 'RainToday' field.
   * @return The value of the 'RainToday' field.
   */
  public java.lang.CharSequence getRainToday() {
    return RainToday;
  }

  /**
   * Sets the value of the 'RainToday' field.
   * @param value the value to set.
   */
  public void setRainToday(java.lang.CharSequence value) {
    this.RainToday = value;
  }

  /**
   * Gets the value of the 'RISK_MM' field.
   * @return The value of the 'RISK_MM' field.
   */
  public java.lang.CharSequence getRISKMM() {
    return RISK_MM;
  }

  /**
   * Sets the value of the 'RISK_MM' field.
   * @param value the value to set.
   */
  public void setRISKMM(java.lang.CharSequence value) {
    this.RISK_MM = value;
  }

  /**
   * Gets the value of the 'RainTomorrow' field.
   * @return The value of the 'RainTomorrow' field.
   */
  public java.lang.CharSequence getRainTomorrow() {
    return RainTomorrow;
  }

  /**
   * Sets the value of the 'RainTomorrow' field.
   * @param value the value to set.
   */
  public void setRainTomorrow(java.lang.CharSequence value) {
    this.RainTomorrow = value;
  }

  /**
   * Creates a new Weather RecordBuilder.
   * @return A new Weather RecordBuilder
   */
  public static org.example.type.avro.Weather.Builder newBuilder() {
    return new org.example.type.avro.Weather.Builder();
  }

  /**
   * Creates a new Weather RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Weather RecordBuilder
   */
  public static org.example.type.avro.Weather.Builder newBuilder(org.example.type.avro.Weather.Builder other) {
    return new org.example.type.avro.Weather.Builder(other);
  }

  /**
   * Creates a new Weather RecordBuilder by copying an existing Weather instance.
   * @param other The existing instance to copy.
   * @return A new Weather RecordBuilder
   */
  public static org.example.type.avro.Weather.Builder newBuilder(org.example.type.avro.Weather other) {
    return new org.example.type.avro.Weather.Builder(other);
  }

  /**
   * RecordBuilder for Weather instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Weather>
    implements org.apache.avro.data.RecordBuilder<Weather> {

    private java.lang.CharSequence MinTemp;
    private java.lang.CharSequence MaxTemp;
    private java.lang.CharSequence Rainfall;
    private java.lang.CharSequence Evaporation;
    private java.lang.CharSequence Sunshine;
    private java.lang.CharSequence WindGustDir;
    private java.lang.CharSequence WindGustSpeed;
    private java.lang.CharSequence WindDir9am;
    private java.lang.CharSequence WindDir3pm;
    private java.lang.CharSequence WindSpeed9am;
    private java.lang.CharSequence WindSpeed3pm;
    private java.lang.CharSequence Humidity9am;
    private java.lang.CharSequence Humidity3pm;
    private java.lang.CharSequence Pressure9am;
    private java.lang.CharSequence Pressure3pm;
    private java.lang.CharSequence Cloud9am;
    private java.lang.CharSequence Cloud3pm;
    private java.lang.CharSequence Temp9am;
    private java.lang.CharSequence Temp3pm;
    private java.lang.CharSequence RainToday;
    private java.lang.CharSequence RISK_MM;
    private java.lang.CharSequence RainTomorrow;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.type.avro.Weather.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MinTemp)) {
        this.MinTemp = data().deepCopy(fields()[0].schema(), other.MinTemp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MaxTemp)) {
        this.MaxTemp = data().deepCopy(fields()[1].schema(), other.MaxTemp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Rainfall)) {
        this.Rainfall = data().deepCopy(fields()[2].schema(), other.Rainfall);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Evaporation)) {
        this.Evaporation = data().deepCopy(fields()[3].schema(), other.Evaporation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Sunshine)) {
        this.Sunshine = data().deepCopy(fields()[4].schema(), other.Sunshine);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.WindGustDir)) {
        this.WindGustDir = data().deepCopy(fields()[5].schema(), other.WindGustDir);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.WindGustSpeed)) {
        this.WindGustSpeed = data().deepCopy(fields()[6].schema(), other.WindGustSpeed);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.WindDir9am)) {
        this.WindDir9am = data().deepCopy(fields()[7].schema(), other.WindDir9am);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.WindDir3pm)) {
        this.WindDir3pm = data().deepCopy(fields()[8].schema(), other.WindDir3pm);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.WindSpeed9am)) {
        this.WindSpeed9am = data().deepCopy(fields()[9].schema(), other.WindSpeed9am);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.WindSpeed3pm)) {
        this.WindSpeed3pm = data().deepCopy(fields()[10].schema(), other.WindSpeed3pm);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.Humidity9am)) {
        this.Humidity9am = data().deepCopy(fields()[11].schema(), other.Humidity9am);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.Humidity3pm)) {
        this.Humidity3pm = data().deepCopy(fields()[12].schema(), other.Humidity3pm);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.Pressure9am)) {
        this.Pressure9am = data().deepCopy(fields()[13].schema(), other.Pressure9am);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.Pressure3pm)) {
        this.Pressure3pm = data().deepCopy(fields()[14].schema(), other.Pressure3pm);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.Cloud9am)) {
        this.Cloud9am = data().deepCopy(fields()[15].schema(), other.Cloud9am);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Cloud3pm)) {
        this.Cloud3pm = data().deepCopy(fields()[16].schema(), other.Cloud3pm);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Temp9am)) {
        this.Temp9am = data().deepCopy(fields()[17].schema(), other.Temp9am);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.Temp3pm)) {
        this.Temp3pm = data().deepCopy(fields()[18].schema(), other.Temp3pm);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.RainToday)) {
        this.RainToday = data().deepCopy(fields()[19].schema(), other.RainToday);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RISK_MM)) {
        this.RISK_MM = data().deepCopy(fields()[20].schema(), other.RISK_MM);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.RainTomorrow)) {
        this.RainTomorrow = data().deepCopy(fields()[21].schema(), other.RainTomorrow);
        fieldSetFlags()[21] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Weather instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.type.avro.Weather other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.MinTemp)) {
        this.MinTemp = data().deepCopy(fields()[0].schema(), other.MinTemp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MaxTemp)) {
        this.MaxTemp = data().deepCopy(fields()[1].schema(), other.MaxTemp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Rainfall)) {
        this.Rainfall = data().deepCopy(fields()[2].schema(), other.Rainfall);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Evaporation)) {
        this.Evaporation = data().deepCopy(fields()[3].schema(), other.Evaporation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Sunshine)) {
        this.Sunshine = data().deepCopy(fields()[4].schema(), other.Sunshine);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.WindGustDir)) {
        this.WindGustDir = data().deepCopy(fields()[5].schema(), other.WindGustDir);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.WindGustSpeed)) {
        this.WindGustSpeed = data().deepCopy(fields()[6].schema(), other.WindGustSpeed);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.WindDir9am)) {
        this.WindDir9am = data().deepCopy(fields()[7].schema(), other.WindDir9am);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.WindDir3pm)) {
        this.WindDir3pm = data().deepCopy(fields()[8].schema(), other.WindDir3pm);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.WindSpeed9am)) {
        this.WindSpeed9am = data().deepCopy(fields()[9].schema(), other.WindSpeed9am);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.WindSpeed3pm)) {
        this.WindSpeed3pm = data().deepCopy(fields()[10].schema(), other.WindSpeed3pm);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.Humidity9am)) {
        this.Humidity9am = data().deepCopy(fields()[11].schema(), other.Humidity9am);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.Humidity3pm)) {
        this.Humidity3pm = data().deepCopy(fields()[12].schema(), other.Humidity3pm);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.Pressure9am)) {
        this.Pressure9am = data().deepCopy(fields()[13].schema(), other.Pressure9am);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.Pressure3pm)) {
        this.Pressure3pm = data().deepCopy(fields()[14].schema(), other.Pressure3pm);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.Cloud9am)) {
        this.Cloud9am = data().deepCopy(fields()[15].schema(), other.Cloud9am);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.Cloud3pm)) {
        this.Cloud3pm = data().deepCopy(fields()[16].schema(), other.Cloud3pm);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Temp9am)) {
        this.Temp9am = data().deepCopy(fields()[17].schema(), other.Temp9am);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.Temp3pm)) {
        this.Temp3pm = data().deepCopy(fields()[18].schema(), other.Temp3pm);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.RainToday)) {
        this.RainToday = data().deepCopy(fields()[19].schema(), other.RainToday);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RISK_MM)) {
        this.RISK_MM = data().deepCopy(fields()[20].schema(), other.RISK_MM);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.RainTomorrow)) {
        this.RainTomorrow = data().deepCopy(fields()[21].schema(), other.RainTomorrow);
        fieldSetFlags()[21] = true;
      }
    }

    /**
      * Gets the value of the 'MinTemp' field.
      * @return The value.
      */
    public java.lang.CharSequence getMinTemp() {
      return MinTemp;
    }

    /**
      * Sets the value of the 'MinTemp' field.
      * @param value The value of 'MinTemp'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setMinTemp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.MinTemp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MinTemp' field has been set.
      * @return True if the 'MinTemp' field has been set, false otherwise.
      */
    public boolean hasMinTemp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'MinTemp' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearMinTemp() {
      MinTemp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'MaxTemp' field.
      * @return The value.
      */
    public java.lang.CharSequence getMaxTemp() {
      return MaxTemp;
    }

    /**
      * Sets the value of the 'MaxTemp' field.
      * @param value The value of 'MaxTemp'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setMaxTemp(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MaxTemp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'MaxTemp' field has been set.
      * @return True if the 'MaxTemp' field has been set, false otherwise.
      */
    public boolean hasMaxTemp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'MaxTemp' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearMaxTemp() {
      MaxTemp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Rainfall' field.
      * @return The value.
      */
    public java.lang.CharSequence getRainfall() {
      return Rainfall;
    }

    /**
      * Sets the value of the 'Rainfall' field.
      * @param value The value of 'Rainfall'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setRainfall(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Rainfall = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Rainfall' field has been set.
      * @return True if the 'Rainfall' field has been set, false otherwise.
      */
    public boolean hasRainfall() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Rainfall' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearRainfall() {
      Rainfall = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Evaporation' field.
      * @return The value.
      */
    public java.lang.CharSequence getEvaporation() {
      return Evaporation;
    }

    /**
      * Sets the value of the 'Evaporation' field.
      * @param value The value of 'Evaporation'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setEvaporation(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Evaporation = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Evaporation' field has been set.
      * @return True if the 'Evaporation' field has been set, false otherwise.
      */
    public boolean hasEvaporation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Evaporation' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearEvaporation() {
      Evaporation = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'Sunshine' field.
      * @return The value.
      */
    public java.lang.CharSequence getSunshine() {
      return Sunshine;
    }

    /**
      * Sets the value of the 'Sunshine' field.
      * @param value The value of 'Sunshine'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setSunshine(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.Sunshine = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'Sunshine' field has been set.
      * @return True if the 'Sunshine' field has been set, false otherwise.
      */
    public boolean hasSunshine() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'Sunshine' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearSunshine() {
      Sunshine = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindGustDir' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindGustDir() {
      return WindGustDir;
    }

    /**
      * Sets the value of the 'WindGustDir' field.
      * @param value The value of 'WindGustDir'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindGustDir(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.WindGustDir = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'WindGustDir' field has been set.
      * @return True if the 'WindGustDir' field has been set, false otherwise.
      */
    public boolean hasWindGustDir() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'WindGustDir' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindGustDir() {
      WindGustDir = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindGustSpeed' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindGustSpeed() {
      return WindGustSpeed;
    }

    /**
      * Sets the value of the 'WindGustSpeed' field.
      * @param value The value of 'WindGustSpeed'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindGustSpeed(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.WindGustSpeed = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'WindGustSpeed' field has been set.
      * @return True if the 'WindGustSpeed' field has been set, false otherwise.
      */
    public boolean hasWindGustSpeed() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'WindGustSpeed' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindGustSpeed() {
      WindGustSpeed = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindDir9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindDir9am() {
      return WindDir9am;
    }

    /**
      * Sets the value of the 'WindDir9am' field.
      * @param value The value of 'WindDir9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindDir9am(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.WindDir9am = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'WindDir9am' field has been set.
      * @return True if the 'WindDir9am' field has been set, false otherwise.
      */
    public boolean hasWindDir9am() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'WindDir9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindDir9am() {
      WindDir9am = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindDir3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindDir3pm() {
      return WindDir3pm;
    }

    /**
      * Sets the value of the 'WindDir3pm' field.
      * @param value The value of 'WindDir3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindDir3pm(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.WindDir3pm = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'WindDir3pm' field has been set.
      * @return True if the 'WindDir3pm' field has been set, false otherwise.
      */
    public boolean hasWindDir3pm() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'WindDir3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindDir3pm() {
      WindDir3pm = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindSpeed9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindSpeed9am() {
      return WindSpeed9am;
    }

    /**
      * Sets the value of the 'WindSpeed9am' field.
      * @param value The value of 'WindSpeed9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindSpeed9am(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.WindSpeed9am = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'WindSpeed9am' field has been set.
      * @return True if the 'WindSpeed9am' field has been set, false otherwise.
      */
    public boolean hasWindSpeed9am() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'WindSpeed9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindSpeed9am() {
      WindSpeed9am = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'WindSpeed3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getWindSpeed3pm() {
      return WindSpeed3pm;
    }

    /**
      * Sets the value of the 'WindSpeed3pm' field.
      * @param value The value of 'WindSpeed3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setWindSpeed3pm(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.WindSpeed3pm = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'WindSpeed3pm' field has been set.
      * @return True if the 'WindSpeed3pm' field has been set, false otherwise.
      */
    public boolean hasWindSpeed3pm() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'WindSpeed3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearWindSpeed3pm() {
      WindSpeed3pm = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'Humidity9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getHumidity9am() {
      return Humidity9am;
    }

    /**
      * Sets the value of the 'Humidity9am' field.
      * @param value The value of 'Humidity9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setHumidity9am(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.Humidity9am = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'Humidity9am' field has been set.
      * @return True if the 'Humidity9am' field has been set, false otherwise.
      */
    public boolean hasHumidity9am() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'Humidity9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearHumidity9am() {
      Humidity9am = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'Humidity3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getHumidity3pm() {
      return Humidity3pm;
    }

    /**
      * Sets the value of the 'Humidity3pm' field.
      * @param value The value of 'Humidity3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setHumidity3pm(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.Humidity3pm = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'Humidity3pm' field has been set.
      * @return True if the 'Humidity3pm' field has been set, false otherwise.
      */
    public boolean hasHumidity3pm() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'Humidity3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearHumidity3pm() {
      Humidity3pm = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'Pressure9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getPressure9am() {
      return Pressure9am;
    }

    /**
      * Sets the value of the 'Pressure9am' field.
      * @param value The value of 'Pressure9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setPressure9am(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.Pressure9am = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'Pressure9am' field has been set.
      * @return True if the 'Pressure9am' field has been set, false otherwise.
      */
    public boolean hasPressure9am() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'Pressure9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearPressure9am() {
      Pressure9am = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'Pressure3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getPressure3pm() {
      return Pressure3pm;
    }

    /**
      * Sets the value of the 'Pressure3pm' field.
      * @param value The value of 'Pressure3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setPressure3pm(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.Pressure3pm = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'Pressure3pm' field has been set.
      * @return True if the 'Pressure3pm' field has been set, false otherwise.
      */
    public boolean hasPressure3pm() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'Pressure3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearPressure3pm() {
      Pressure3pm = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'Cloud9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getCloud9am() {
      return Cloud9am;
    }

    /**
      * Sets the value of the 'Cloud9am' field.
      * @param value The value of 'Cloud9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setCloud9am(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.Cloud9am = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'Cloud9am' field has been set.
      * @return True if the 'Cloud9am' field has been set, false otherwise.
      */
    public boolean hasCloud9am() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'Cloud9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearCloud9am() {
      Cloud9am = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'Cloud3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getCloud3pm() {
      return Cloud3pm;
    }

    /**
      * Sets the value of the 'Cloud3pm' field.
      * @param value The value of 'Cloud3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setCloud3pm(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.Cloud3pm = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'Cloud3pm' field has been set.
      * @return True if the 'Cloud3pm' field has been set, false otherwise.
      */
    public boolean hasCloud3pm() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'Cloud3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearCloud3pm() {
      Cloud3pm = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'Temp9am' field.
      * @return The value.
      */
    public java.lang.CharSequence getTemp9am() {
      return Temp9am;
    }

    /**
      * Sets the value of the 'Temp9am' field.
      * @param value The value of 'Temp9am'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setTemp9am(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.Temp9am = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'Temp9am' field has been set.
      * @return True if the 'Temp9am' field has been set, false otherwise.
      */
    public boolean hasTemp9am() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'Temp9am' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearTemp9am() {
      Temp9am = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'Temp3pm' field.
      * @return The value.
      */
    public java.lang.CharSequence getTemp3pm() {
      return Temp3pm;
    }

    /**
      * Sets the value of the 'Temp3pm' field.
      * @param value The value of 'Temp3pm'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setTemp3pm(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.Temp3pm = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'Temp3pm' field has been set.
      * @return True if the 'Temp3pm' field has been set, false otherwise.
      */
    public boolean hasTemp3pm() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'Temp3pm' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearTemp3pm() {
      Temp3pm = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'RainToday' field.
      * @return The value.
      */
    public java.lang.CharSequence getRainToday() {
      return RainToday;
    }

    /**
      * Sets the value of the 'RainToday' field.
      * @param value The value of 'RainToday'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setRainToday(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.RainToday = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'RainToday' field has been set.
      * @return True if the 'RainToday' field has been set, false otherwise.
      */
    public boolean hasRainToday() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'RainToday' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearRainToday() {
      RainToday = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'RISK_MM' field.
      * @return The value.
      */
    public java.lang.CharSequence getRISKMM() {
      return RISK_MM;
    }

    /**
      * Sets the value of the 'RISK_MM' field.
      * @param value The value of 'RISK_MM'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setRISKMM(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.RISK_MM = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'RISK_MM' field has been set.
      * @return True if the 'RISK_MM' field has been set, false otherwise.
      */
    public boolean hasRISKMM() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'RISK_MM' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearRISKMM() {
      RISK_MM = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'RainTomorrow' field.
      * @return The value.
      */
    public java.lang.CharSequence getRainTomorrow() {
      return RainTomorrow;
    }

    /**
      * Sets the value of the 'RainTomorrow' field.
      * @param value The value of 'RainTomorrow'.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder setRainTomorrow(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.RainTomorrow = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'RainTomorrow' field has been set.
      * @return True if the 'RainTomorrow' field has been set, false otherwise.
      */
    public boolean hasRainTomorrow() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'RainTomorrow' field.
      * @return This builder.
      */
    public org.example.type.avro.Weather.Builder clearRainTomorrow() {
      RainTomorrow = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public Weather build() {
      try {
        Weather record = new Weather();
        record.MinTemp = fieldSetFlags()[0] ? this.MinTemp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.MaxTemp = fieldSetFlags()[1] ? this.MaxTemp : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Rainfall = fieldSetFlags()[2] ? this.Rainfall : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Evaporation = fieldSetFlags()[3] ? this.Evaporation : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.Sunshine = fieldSetFlags()[4] ? this.Sunshine : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.WindGustDir = fieldSetFlags()[5] ? this.WindGustDir : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.WindGustSpeed = fieldSetFlags()[6] ? this.WindGustSpeed : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.WindDir9am = fieldSetFlags()[7] ? this.WindDir9am : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.WindDir3pm = fieldSetFlags()[8] ? this.WindDir3pm : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.WindSpeed9am = fieldSetFlags()[9] ? this.WindSpeed9am : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.WindSpeed3pm = fieldSetFlags()[10] ? this.WindSpeed3pm : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.Humidity9am = fieldSetFlags()[11] ? this.Humidity9am : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.Humidity3pm = fieldSetFlags()[12] ? this.Humidity3pm : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.Pressure9am = fieldSetFlags()[13] ? this.Pressure9am : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.Pressure3pm = fieldSetFlags()[14] ? this.Pressure3pm : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.Cloud9am = fieldSetFlags()[15] ? this.Cloud9am : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.Cloud3pm = fieldSetFlags()[16] ? this.Cloud3pm : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.Temp9am = fieldSetFlags()[17] ? this.Temp9am : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.Temp3pm = fieldSetFlags()[18] ? this.Temp3pm : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.RainToday = fieldSetFlags()[19] ? this.RainToday : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.RISK_MM = fieldSetFlags()[20] ? this.RISK_MM : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.RainTomorrow = fieldSetFlags()[21] ? this.RainTomorrow : (java.lang.CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
